//
//  File.swift
//
//
//  Created by 박혜운 on 9/17/24.
//

import SwiftUI

// Image 이름을 나타내는 커스텀 타입


public extension ImageResource {
  /// The "Share" asset catalog image resource.
  static let analysis_iconW = ImageResource(name: "analysis_icon", bundle: .module)
  static let apple_buttonW = ImageResource(name: "apple_button", bundle: .module)
  static let google_buttonW = ImageResource(name: "google_button", bundle: .module)
  static let kakao_buttonW = ImageResource(name: "kakao_button", bundle: .module)
  static let logo_imgeW = ImageResource(name: "logo_imge", bundle: .module)
  static let logoText_imgeW = ImageResource(name: "logoText_imge", bundle: .module)
  static let rock_imageW = ImageResource(name: "rock_image", bundle: .module)
  static let showcase_scentWineW = ImageResource(name: "showcase_scentWine", bundle: .module)
  static let showcase_SourWineW = ImageResource(name: "showcase_SourWine", bundle: .module)
  static let welcome_WineGroupW = ImageResource(name: "welcome_WineGroup", bundle: .module)
  static let navigationBack_buttonW = ImageResource(name: "navigationBack_button", bundle: .module)
  static let text_delete_iconW = ImageResource(name: "text_delete_icon", bundle: .module)
  static let analysisBackgroundW = ImageResource(name: "analysisBackground", bundle: .module)
  static let analysisLoadingW = ImageResource(name: "analysisLoading", bundle: .module)
  static let analysisNoteIconW = ImageResource(name: "analysisNoteIcon", bundle: .module)
  static let arrowBottomW = ImageResource(name: "arrowBottom", bundle: .module)
  static let arrowTopW = ImageResource(name: "arrowTop", bundle: .module)
  static let wineBottleW = ImageResource(name: "wineBottle", bundle: .module)
  static let ic_arrow_rightW = ImageResource(name: "ic_arrow_right", bundle: .module)
  static let star_1W = ImageResource(name: "star_1", bundle: .module)
  static let tipCardW = ImageResource(name: "tipCard", bundle: .module)
  static let etc_illustW = ImageResource(name: "etc_illust", bundle: .module)
  static let port_illustW = ImageResource(name: "port_illust", bundle: .module)
  static let red_illustW = ImageResource(name: "red_illust", bundle: .module)
  static let rose_illustW = ImageResource(name: "rose_illust", bundle: .module)
  static let sparkl_illustW = ImageResource(name: "sparkl_illust", bundle: .module)
  static let white_illustW = ImageResource(name: "white_illust", bundle: .module)
  static let blank_likeList_backgroundW = ImageResource(name: "blank_likeList_background", bundle: .module)
  static let blank_noteW = ImageResource(name: "blank_note", bundle: .module)
  static let blank_shopList_backgroundW = ImageResource(name: "blank_shopList_background", bundle: .module)
  static let dot_markerW = ImageResource(name: "dot_marker", bundle: .module)
  static let empty_markerW = ImageResource(name: "empty_marker", bundle: .module)
  static let fill_markerW = ImageResource(name: "fill_marker", bundle: .module)
  static let info_clockW = ImageResource(name: "info_clock", bundle: .module)
  static let info_markW = ImageResource(name: "info_mark", bundle: .module)
  static let info_phoneW = ImageResource(name: "info_phone", bundle: .module)
  static let location_reloadW = ImageResource(name: "location_reload", bundle: .module)
  static let location_trackerW = ImageResource(name: "location_tracker", bundle: .module)
  static let maker_myPlaceW = ImageResource(name: "maker_myPlace", bundle: .module)
  static let map_listW = ImageResource(name: "map_list", bundle: .module)
  static let marker_backgroundW = ImageResource(name: "marker_background", bundle: .module)
  static let marker_bottleShopW = ImageResource(name: "marker_bottleShop", bundle: .module)
  static let marker_cafeW = ImageResource(name: "marker_cafe", bundle: .module)
  static let marker_pubW = ImageResource(name: "marker_pub", bundle: .module)
  static let marker_restaurantW = ImageResource(name: "marker_restaurant", bundle: .module)
  static let marker_wineBarW = ImageResource(name: "marker_wineBar", bundle: .module)
  static let white_markerW = ImageResource(name: "white_marker", bundle: .module)
  static let UserIconW = ImageResource(name: "UserIcon", bundle: .module)
  static let activeWineIconW = ImageResource(name: "activeWineIcon", bundle: .module)
  static let cameraIconW = ImageResource(name: "cameraIcon", bundle: .module)
  static let checkIconW = ImageResource(name: "checkIcon", bundle: .module)
  static let complete_NoteW = ImageResource(name: "complete_Note", bundle: .module)
  static let defaultWineIconW = ImageResource(name: "defaultWineIcon", bundle: .module)
  static let emptyNoteIconW = ImageResource(name: "emptyNoteIcon", bundle: .module)
  static let filterArrowW = ImageResource(name: "filterArrow", bundle: .module)
  static let filterIconW = ImageResource(name: "filterIcon", bundle: .module)
  static let filterXIconW = ImageResource(name: "filterXIcon", bundle: .module)
  static let ic_searchW = ImageResource(name: "ic_search", bundle: .module)
  static let imageXW = ImageResource(name: "imageX", bundle: .module)
  static let initArrowW = ImageResource(name: "initArrow", bundle: .module)
  static let noSearchW = ImageResource(name: "noSearch", bundle: .module)
  static let noteBackgroundW = ImageResource(name: "noteBackground", bundle: .module)
  static let noteColorImageW = ImageResource(name: "noteColorImage", bundle: .module)
  static let noteDetailArrowBodyW = ImageResource(name: "noteDetailArrowBody", bundle: .module)
  static let noteDetailArrowHeaderW = ImageResource(name: "noteDetailArrowHeader", bundle: .module)
  static let noteDoneBackgroundW = ImageResource(name: "noteDoneBackground", bundle: .module)
  static let pencilIconW = ImageResource(name: "pencilIcon", bundle: .module)
  static let reloadIconW = ImageResource(name: "reloadIcon", bundle: .module)
  static let settingIconW = ImageResource(name: "settingIcon", bundle: .module)
  static let smellPlusDefaultW = ImageResource(name: "smellPlusDefault", bundle: .module)
  static let smellPlusOpenW = ImageResource(name: "smellPlusOpen", bundle: .module)
  static let wineTicketImageW = ImageResource(name: "wineTicketImage", bundle: .module)
  static let home_iconW = ImageResource(name: "home_icon", bundle: .module)
  static let map_iconW = ImageResource(name: "map_icon", bundle: .module)
  static let mypage_iconW = ImageResource(name: "mypage_icon", bundle: .module)
  static let note_iconW = ImageResource(name: "note_icon", bundle: .module)
  static let selected_home_iconW = ImageResource(name: "selected_home_icon", bundle: .module)
  static let selected_map_iconW = ImageResource(name: "selected_map_icon", bundle: .module)
  static let selected_mypage_iconW = ImageResource(name: "selected_mypage_icon", bundle: .module)
  static let selected_note_iconW = ImageResource(name: "selected_note_icon", bundle: .module)
}
